# PlatformIO pre-build step: gzip the SoftAP portal once so the node serves
# ~12 KB compressed (gzip content encoding) instead of 68 KB of HTML each load.
#
# Source of truth stays include/wifi_setup_html.h (edit that file). This
# writes include/generated/wifi_setup_html_gz.h only when the HTML changed.
import gzip
import os
import re
import zlib

try:
    Import("env")  # noqa: F821  (PlatformIO SCons)
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(ROOT, "include", "wifi_setup_html.h")
OUT_DIR = os.path.join(ROOT, "include", "generated")
OUT = os.path.join(OUT_DIR, "wifi_setup_html_gz.h")


def build():
    text = open(SRC, "r", encoding="utf-8").read()
    m = re.search(r'R"WIFIHTML\((.*)\)WIFIHTML"', text, re.S)
    if not m:
        raise SystemExit("gzip_portal: raw string not found in " + SRC)
    html = m.group(1).encode("utf-8")
    # mtime=0 keeps the output (and the ETag) stable across builds.
    gz = gzip.compress(html, compresslevel=9, mtime=0)
    etag = "%08x" % (zlib.crc32(gz) & 0xFFFFFFFF)
    rows = []
    for i in range(0, len(gz), 20):
        rows.append("  " + ",".join("0x%02x" % b for b in gz[i:i + 20]) + ",")
    body = (
        "#pragma once\n\n"
        "// Generated by scripts/gzip_portal.py from wifi_setup_html.h. Do not edit.\n\n"
        "#include <pgmspace.h>\n#include <stddef.h>\n#include <stdint.h>\n\n"
        "static const char kWifiSetupHtmlEtag[] = \"\\\"%s\\\"\";\n"
        "static const size_t kWifiSetupHtmlGzLen = %d;\n"
        "static const uint8_t kWifiSetupHtmlGz[] PROGMEM = {\n%s\n};\n"
        % (etag, len(gz), "\n".join(rows))
    )
    os.makedirs(OUT_DIR, exist_ok=True)
    if os.path.exists(OUT) and open(OUT, "r", encoding="utf-8").read() == body:
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("gzip_portal: %d -> %d bytes (etag %s)" % (len(html), len(gz), etag))


build()
